Repository opossum-labs/opossum, pull requests merged in 2025-09, with the labels that each got.

#543 537 UI is unresponsive when cli has not been built and run simulation is pressed
  opossum_gui/src/components/simulation/simulation_window.rs
Labels: bug

#547 fix: :bug: Graph store now cleared on GUI side when loading opm file
  opossum_gui/src/components/scenery_editor/graph_store.rs
Labels: bug, gui

#558 fix: :bug: Z-index on selection nodes working again
  opossum_gui/src/components/scenery_editor/graph_store.rs
  opossum_gui/src/components/scenery_editor/node/node_component.rs
Labels: bug, gui

#561 560 pasting nodes sometimes not working
  opossum_gui/src/components/scenery_editor/graph_editor/graph_editor_component.rs
  opossum_gui/src/components/scenery_editor/graph_store.rs
Labels: bug

#563 562 revive minimize maximize close drag controls
  opossum_cli/src/console.rs
  opossum_gui/src/components/app.rs
  opossum_gui/src/components/menu_bar/controls/controls_menu.rs
  opossum_gui/src/components/menu_bar/controls/mod.rs
  opossum_gui/src/components/menu_bar/menu_bar_component.rs
  opossum_gui/src/components/plot/mod.rs
  opossum_gui/src/components/scenery_editor/graph_editor/graph_editor_component.rs
  opossum_gui/src/components/scenery_editor/node/node_component.rs
  opossum_gui/src/components/simulation/utils.rs
  opossum_gui/src/main.rs
Labels: enhancement, gui

#565 564 copying of nodes does nor work robustly
  opossum_gui/src/components/scenery_editor/graph_editor/graph_editor_component.rs
  opossum_gui/src/components/scenery_editor/graph_editor/hooks.rs
  opossum_gui/src/components/scenery_editor/node/node_component.rs
Labels: bug, gui

#598 fix: :bug: Fiex subtle layout bug in Help menu
  opossum_gui/src/components/menu_bar/menu_bar_component.rs
Labels: bug

#599 fix: :bug: Fix missing deselction after delete node.
  opossum_gui/src/components/scenery_editor/node/node_component.rs
Labels: bug

#600 fix: :bug: Synchronize backend and frontend at start.
  opossum_gui/src/components/app.rs
  opossum_gui/src/components/menu_bar/controls/controls_menu.rs
  opossum_gui/src/components/menu_bar/menu_bar_component.rs
  opossum_gui/src/components/menu_bar/mod.rs
  opossum_gui/src/components/menu_bar/path_helper.rs
  opossum_gui/src/components/scenery_editor/node/node_component.rs
Labels: bug, enhancement

#604 fix: :bug: Delete node also deletes a cascade of (nested) refs
  opossum_core/src/nodes/node_group/optic_graph.rs
Labels: bug

#605 fix: :bug: Setter function of gaussian spectral editor was falsely us…
  opossum_gui/src/components/node_editor/optical_node_editor/properties_editor/light_data_editor/ray_source_editor/distribution_editor/spectral_distribution_editor/gaussian_editor.rs
  opossum_gui/src/components/node_editor/optical_node_editor/properties_editor/mod.rs
Labels: bug, gui

#608 feat: :sparkles: Set global position of a source at origin by default.
  opossum_core/examples/fluence_helper_test.rs
  opossum_core/examples/fluence_test.rs
  opossum_core/examples/folded_telescope.rs
  opossum_core/examples/fresnel_coating.rs
  opossum_core/examples/ghost_focus.rs
  opossum_core/examples/grating_examples/grating_examples.rs
  opossum_core/examples/hhts/hhts.rs
  opossum_core/examples/image_field.rs
  opossum_core/examples/off_center_position_distribution.rs
  opossum_core/examples/prism_dispersion.rs
  opossum_core/examples/spectrometer_test.rs
  opossum_core/examples/workshop_02_kepler_real_lenses_chromatism.rs
  opossum_core/examples/workshop_03_kepler_real_lenses_wavefront.rs
  opossum_core/examples/workshop_04_kepler_real_lenses_imaging_point.rs
  opossum_core/examples/workshop_05_kepler_real_lenses_image_field.rs
  opossum_core/examples/workshop_08_reference_node.rs
  opossum_core/examples/workshop_09_phelix.rs
  opossum_core/examples/workshop_09_phelix_copy.rs
  opossum_core/examples/workshop_11_ghostfocus.rs
  opossum_core/src/nodes/source.rs
  opossum_core/src/nodes/source_helper.rs
Labels: enhancement
